### ISSUE TITLE
Current pypi version doesn't seem to include `extract_scfa`

### ISSUE THREAD

**Issue by pseusys** [Askaholic/faf-replay-parser-python#5]
Function `extract_scfa` was not found with library installed via `faf-replay-parser[faf]`.  
Neither `extra 'faf'` was provided.  

Output of `pip3 install faf-replay-parser[faf]` looked like: `WARNING: faf-replay-parser 0.5.2 does not provide the extra 'faf'`.
Python version: 3.9, OS: Windows 10.

**Comment by pseusys** [comment]
Looks like [the latest release](https://github.com/Askaholic/faf-replay-parser-python/releases/tag/v0.5.2) that was uploaded to PyPi using GitHub actions was exactly 10 commits ago - right before the `extract_scfa` function was added.

**Comment by Askaholic** [comment]
Hmm, I don’t remember why I didn’t make a release for it. I remember I was working on this package and then I started working on the Rust library, so maybe I just forgot or I was going to add something else into the release. But I haven’t worked on it in a while so maybe I can just release the main branch as is.

Thanks for opening the issue!

**Comment by pseusys** [comment]
I guess it may be released as `0.52-dev` version or something, the only issue is that the last statement in main page README file is currently misleading.

**Comment by Askaholic** [comment]
Yep. If you do need the function you can also copy paste it for now since it’s implemented in python and pretty short:

https://github.com/Askaholic/faf-replay-parser-python/blob/main/fafreplay/__init__.py

**Comment by Askaholic** [comment]
Ok thanks! I’ll try to find some time to make another release.

**Comment by Askaholic** [comment]
I made a release for version `0.5.3` and it looks like the github actions successfully uploaded it to pypi. Could you confirm if it works for you?

**Comment by pseusys** [comment]
Yep, sorry for no answer for a long time, now it works as expected!
Thank you for that library!
